sumo:
  scenario: ../sumo/scenario/dua.static.sumocfg
  step_length: 1.0
  fcd_output: ../sumo/output/fcd_output_static_27000_37000.txt
  begin: 27000
  end: 37000

parse_sumo:
  fcd_output: ../sumo/output/fcd_output_static_27000_37000.txt
  ouput_dir: /home/surveillance/openmessaging-benchmark/parsed/locations/static_27000_37000_locations.data
  low_time: 27000
  high_time: 37000

static_load:
  numClients: 6
  iterations: 200
  minX: 33.7757
  minY: 85.3963
  maxX: 34.7757
  maxY: 86.3963
  outfile: /home/surveillance/openmessaging-benchmark/parsed/locations/static_locations_c_6_i_200.data

split:
  input_file: /home/surveillance/openmessaging-benchmark/parsed/locations/static_locations_c_6_i_200.data
  output_dir: /home/surveillance/openmessaging-benchmark/parsed/split/
  num_workers: 3

workload:
  topics: 1
  partitionsPerTopic: 16
  messageSize: 1024
  payloadFile: "1Kb"
  consumerPerSubscription: 1
  producersPerTopic: 1
  producerRate: 50000
  testDurationMinutes: 3
  numClients: 3
    
index_config:
  blockSize: 0.001
  indexType: GEOHASH
  minLat: 33.7757
  minLng: 85.3963
  maxLat: 34.7757
  maxLng: 86.3963

automation:
  benchmark_home: "/home/surveillance/openmessaging-benchmark"
  pulsar_home: "/home/surveillance/pulsar"
  broker: 192.168.124.174
  clients: "192.168.124.141 192.168.124.207 192.168.124.95"
  driver_config: pulsar-temp.yaml
  data_dir: "parsed/split"