sumo:
  scenario: ../sumo/scenario/dua.static.sumocfg
  step_length: 1.0
  fcd_output: ../sumo/output/fcd_output_static_27000_37000.txt
  begin: 27000
  end: 37000

parse_sumo:
  fcd_output: ../sumo/output/fcd_output_static_27000_37000.txt
  ouput_dir: /home/cetus/new-openmessaging-benchmark/parsed/locations/static_27000_37000_locations.data
  low_time: 27000
  high_time: 37000

static_load:
  numClients: 6
  iterations: 200
  minX: 33.7757
  minY: 85.3963
  maxX: 33.8057
  maxY: 85.4263
  outfile: /home/cetus/new-openmessaging-benchmark/parsed/locations/static_locations_c_6_i_200.data

locations_config:
  numStaticClients: 4
  numMobileClients: 0
  min_lat: 33.7757
  min_lng: 85.3963
  max_lat: 33.8057
  max_lng: 85.4263
  locChangeInterval: 10
  totalDuration: 30
  outfile: /home/cetus/new-openmessaging-benchmark/parsed/locations/static_clients_4.data

split:
  input_file: /home/cetus/new-openmessaging-benchmark/parsed/locations/static_locations_c_6_i_200.data
  output_dir: /home/cetus/new-openmessaging-benchmark/parsed/split/
  num_workers: 1

workload:
  topics: 1
  partitionsPerTopic: 16
  messageSize: 1024
  payloadFile: "1Kb"
  consumerPerSubscription: 1
  producersPerTopic: 1
  producerRate: 5
  testDurationMinutes: 1
  numClients: 1

index_config:
  blockSize: 0.001
  indexType: GEOHASH
  minLat: 33.7757
  minLng: 85.3963
  maxLat: 33.8057
  maxLng: 85.4263

automation:
  benchmark_home: "/home/cetus/new-openmessaging-benchmark"
  pulsar_home: "/home/cetus/pulsar"
  broker: 10.100.1.220
  clients: "10.100.1.252 10.100.1.225 10.100.1.214"
  driver_config: pulsar-temp.yaml
  data_dir: "parsed/split"